esphome:
  name: tempsensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KEY"

ota:
  - platform: esphome
    password: "PWD"

wifi:
  ssid: "SSID"
  password: "PWD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tempsensor Fallback Hotspot"
    password: "PWD"

captive_portal:

sensor:
  - platform: dht
    pin: 33
    temperature:
      name: "Room Temp"
    humidity:
      name: "Room Humidity"
    model: DHT11
    update_interval: 60s
